name: Build Windows EXE v2.0

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyinstaller
        
    - name: Try install pandas_access (optional)
      run: |
        pip install pandas_access
      continue-on-error: true
        
    - name: List Python files
      run: |
        Write-Host "Available Python files:"
        Get-ChildItem -Filter "*.py" | Format-Table Name, Length
        
    - name: Build EXE with mdbtools-win
      run: |
        Write-Host "Building EXE with embedded mdbtools-win..."
        pyinstaller --onefile --windowed --name="SMS_Notification_Clients_v2.0" --add-binary="C:\mdbtools\mdb-tables.exe;mdbtools" --add-binary="C:\mdbtools\mdb-export.exe;mdbtools" --exclude-module=pytest --exclude-module=unittest sms_notification_clients.py
        
    - name: Verify EXE creation
      run: |
        if (Test-Path "dist/SMS_Notification_Clients_v2.0.exe") {
          $exe = Get-Item "dist/SMS_Notification_Clients_v2.0.exe"
          Write-Host "Success! EXE created:"
          Write-Host "  File: $($exe.Name)"
          Write-Host "  Size: $([math]::Round($exe.Length / 1MB, 2)) MB"
          Write-Host "  Path: $($exe.FullName)"
        } else {
          Write-Error "EXE file was not created!"
          Write-Host "Contents of dist folder:"
          Get-ChildItem -Path "dist" -ErrorAction SilentlyContinue | Format-Table
          exit 1
        }
        
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: SMS_Notification_Clients_v2_Windows
        path: dist/SMS_Notification_Clients_v2.0.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SMS_Notification_Clients_v2.0.exe
        name: "SMS Notification Clients v2.0"
        body: |
          ## SMS Notification Clients v2.0
          
          ### Features
          - CSV file support (direct processing)
          - Optional MDB to CSV conversion
          - Windows compatible (no external dependencies)
          - Bulgarian text encoding support
          
          ### Usage
          1. Download the .exe file
          2. Run directly on Windows 10/11
          3. No installation required
          
          File size: ~50-100MB
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}