name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-2022  # Използваме конкретна версия
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pandas_access pyinstaller
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name="SMS_Notification_Clients_v1.0" sms_notification_clients.py
        
    - name: Test EXE (basic)
      run: |
        if (Test-Path "dist/SMS_Notification_Clients_v1.0.exe") {
          Write-Host "EXE file created successfully"
          Get-Item "dist/SMS_Notification_Clients_v1.0.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Error "EXE file not found"
          exit 1
        }
        
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: SMS_Notification_Clients_Windows
        path: dist/SMS_Notification_Clients.exe
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SMS_Notification_Clients.exe
        generate_release_notes: true

# name: Build Windows EXE

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:  # Позволява ръчно стартиране

# jobs:
#   build-windows:
#     runs-on: windows-2022  # Използваме конкретна версия
    
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'
    
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pyinstaller pyodbc
    
#     - name: Build EXE with PyInstaller
#       run: |
#         pyinstaller --onefile --windowed --name="SMS_Notification_Clients" sms_notification_clients.py
    
#     - name: Upload EXE artifact
#       uses: actions/upload-artifact@v4
#       with:
#         name: SMS_Notification_Clients_Windows
#         path: dist/SMS_Notification_Clients.exe
    
#     - name: Create Release (if tag)
#       if: startsWith(github.ref, 'refs/tags/')
#       uses: softprops/action-gh-release@v1
#       with:
#         files: dist/SMS_Notification_Clients.exe
#         generate_release_notes: true